included:
  - Sources
excluded:
  - Pods

disabled_rules:
  - force_cast
  - force_try
  - identifier_name
  - type_body_length
  - trailing_whitespace
  - function_body_length

opt_in_rules:
  - empty_count
  - legacy_constant
  - private_action

line_length:
  warning: 120
  error: 200

file_length:
  warning: 600
  error: 1200

todo:
  severity: warning
  included: ".*.swift"
  match_kinds:
    - comment
